### ISSUE TITLE
Don't ask user to edit code...

### ISSUE THREAD

**Issue by zeruniverse** [BenjaminHae/PwChromeExtension#1]
Instead of asking user to edit code for their pwmanager address, write a config page where the user can do so. Otherwise, you might not be able to put it on Chrome Extension Store.  

If the customevent code is necessary for this extension to work, please merge it to my repository. But I would suggest to calculate those information in this plug-in. And directly post to `check.php`. Then you can retrieve data from `password_ajax.php`

**Comment by BenjaminHae** [comment]
I planned to ask you if it's alright to include the code to your repository when the extension is more mature.

Leaving most of the logic out of the extension makes it easier to follow changes in the main project. That's why I don't want to do the login in the plugin.

**Comment by zeruniverse** [comment]
Then I suggest to make an API.html or API.php. This way, if user don't want to integrate, they can delete this API file.

Sure, you're welcome to include it.

**Comment by zeruniverse** [comment]
It's really impressive to me that you had done so much work. Just two suggestions:
1. Use a global variable for http://%HOST% and load the variable from user config
2. A configuration page that allows users to edit info without editing the code.

I know I mentioned these before but these two things are essential for you to publish the plugin on Chrome Store

**Comment by BenjaminHae** [comment]
I'm planning to change the plugin exactly as you explained.
I'd like to get it running on firefox before. So I won't create another part where I don't now if I have to do porting. Debugging in firefox is really strange. The addon doesn't work(some parts do) but firefox does not show any error.

**Comment by BenjaminHae** [comment]
Alright. It should work. There is a slight timing issue as the content script needs to get the selected host from the settings which is an asynchronous call. Maybe the content script is fast enough. Maybe not.
When it's fast enough the necessary functions in `password.php` are injected. If not it's too late and the addon doesn't get the data. Reloading the page could lead to succes.

**Comment by BenjaminHae** [comment]
Alright the timing issue is important.

**Comment by BenjaminHae** [comment]
Now it's working. Just needs a little change in the original password-manager.
