### ISSUE TITLE
Block dataReady until actions are loaded

### ISSUE THREAD

**Issue by BenjaminHae** [BenjaminHae/PwChromeExtension#24]

**Comment by zeruniverse** [comment]
FYI: Password-Manager 9.11 released.

**Comment by BenjaminHae** [comment]
Cool! I'll see how to publish the addon in one of the stores/or at least as a ready-to-install package over the Christmas break.

**Comment by BenjaminHae** [comment]
Fixed in dc0185230a11f47d55e7527a74afda31c5d11240
