### ISSUE TITLE
Edit function corrupted

### ISSUE THREAD

**Issue by zeruniverse** [BenjaminHae/PwChromeExtension#28]
When click the edit button on addon (pencil icon), it jumps to the password manager website. However, the popped out edit form is empty, where it should have contained the current account information

**Comment by BenjaminHae** [comment]
Are you using Firefox or chrome?

**Comment by zeruniverse** [comment]
Chrome.

I used the demo website.

https://phppasswordmanager.sourceforge.io

**Comment by BenjaminHae** [comment]
Mh I can reproduce it but I don't understand it yet. It works with my productive installation.
So it may take some time to pin it down.

**Comment by BenjaminHae** [comment]
Ok, I think it is a timing issue. I hope it is fixed here: [PwChromeAddon.zip](https://github.com/BenjaminHae/PwChromeExtension/files/644438/PwChromeAddon.zip)

Would you mind trying that version? Just rename the file to `.crx` and import it to chrome. Thanks!

**Comment by zeruniverse** [comment]
Didn't get the time for trying your new version (really busy these days). I think the bug is pretty obvious so I believe your new version works (you won't miss the bug if it's not fixed).

**Comment by BenjaminHae** [comment]
> (you won't miss the bug if it's not fixed).
I disagree as it didn't happen on my local installation.
But I'll just merge my changes and you reopen this ticket if it's still not working.
