### ISSUE TITLE
Newest Chrome doesn't allow enabling extensions not from store

### ISSUE THREAD

**Issue by zeruniverse** [BenjaminHae/PwChromeExtension#32]
![capture](https://cloud.githubusercontent.com/assets/4648756/22087636/dd23dff2-dd93-11e6-9be5-97a4c53cc588.PNG)
  
Please upload to web store

**Comment by BenjaminHae** [comment]
ok, I'll look into it next weekend. It's not as easy as I thought it would be. You first have to pay a little fee and they'll do some checks.

**Comment by BenjaminHae** [comment]
Ok I have to write a "data privacy statement". Do you know of an open source project that has one I could use?

**Comment by zeruniverse** [comment]
I don't think they'll put this in README. If data privacy statement is
available to all users, you might use the statement of other Chome addons.

**Comment by BenjaminHae** [comment]
My google developer account has just been suspended so it may take some more time...

**Comment by BenjaminHae** [comment]
just fyi: I'm on it, but my account is getting suspended everytime I try and there is no way to get feedback for the reason..

**Comment by zeruniverse** [comment]
Oops. Could you register a new account for this?

**Comment by BenjaminHae** [comment]
Well as the first suspension happened only shortly after I uploaded the plugin the first time I think it's because of something in the code. So just creating a new account would probably result in a suspension again.

**Comment by zeruniverse** [comment]
Ok……

**Comment by BenjaminHae** [comment]
I just clicked the "publish" button. In a few workdays the addon should be available for everyone.

**Comment by zeruniverse** [comment]
Excellent

**Comment by BenjaminHae** [comment]
Done =) [Chrome Web Store](https://chrome.google.com/webstore/detail/password-manager/mbfjokpccbakbnnpklkcginkalkijkan)

**Comment by zeruniverse** [comment]
Excellent!
