### ISSUE TITLE
Doesn't work in Chromium - Arch Linux

### ISSUE THREAD

**Issue by zeruniverse** [BenjaminHae/PwChromeExtension#33]
Doesn't work there. I just see the text **Account** but no account for me to choose.

**Comment by BenjaminHae** [comment]
can you please show me the output of the console log from the popup and from the background part of the extension?

You get the output from the popup by right-clicking in the addon-window.
The output from the background is available on the addon manager entry for the password manager addon.

**Comment by zeruniverse** [comment]
Oops, I upgraded my Chromium but it crashed. Didn't you have a Linux system?

**Comment by BenjaminHae** [comment]
Yes, works for me. But I'm using chrome.
I'll look into it when I have time.

**Comment by BenjaminHae** [comment]
Mh, I can't reproduce it using chromium on ubuntu. Could it be that the url for the account doesn't match?

**Comment by zeruniverse** [comment]
Could you try https://phppasswordmanager.sourceforge.io/

?

**Comment by BenjaminHae** [comment]
Works alright.

**Comment by zeruniverse** [comment]
OK... That might be the problem of my browser... Well, it just can't start after upgrade so I can't give more information. I'll simply close this issue.
