### ISSUE TITLE
I'm having a hard time figuring out what the proper url is to put into the Chrome Password Extension. 

### ISSUE THREAD

**Issue by TixFanNews** [BenjaminHae/PwChromeExtension#45]
My site (which is registered by Godaddy and hosted by Square Space) doesn't work. The link for my Google Password Manager page doesn't work. How do I fix this?

**Comment by BenjaminHae** [comment]
Which version of the password manager did you deploy? 11.* is not supported by this plugin.
If you want to use a similar plugin use the completely rewritten version at https://github.com/BenjaminHae/modern-password-manager.

**Comment by TixFanNews** [comment]
Hi,

So I always start with this article: The Man Who Broke Ticketmaster by Vice.<https://www.vice.com/en/article/mgxqb8/the-man-who-broke-ticketmaster>

It tells my story through 2017.

Then if you look up my name “Ken Lowson” on Google you will how many articles I did with the whistle blow of my own creation.

The result:
Experts: Sports fans win in post-COVID ticketing world<https://www.espn.com/espn/otl/story/_/id/31011002/sports-fans-win-post-covid-ticketing>


On Mar 20, 2021, at 11:10 AM, Benjamin Häublein ***@***.******@***.***>> wrote:



Which version of the password manager did you deploy? 11.* is not supported by this plugin.
If you want to use a similar plugin use the completely rewritten version at https://github.com/BenjaminHae/modern-password-manager.

**Comment by BenjaminHae** [comment]
Please reopen this issue if you can provide more precise information on your setup.
